In [2]:
from pynwb import NWBHDF5IO
import warnings
warnings.filterwarnings("ignore")

path = "/Users/sachuriga/Downloads/op6/Rat6_20260629.nwb"

# keep io open so lazy datasets stay readable
io = NWBHDF5IO(path, mode="r", load_namespaces=True)
nwb = io.read()

In [3]:
nwb

root pynwb.file.NWBFile at 0x4601449504
Fields:
  acquisition: {
    lfp <class 'pynwb.base.TimeSeries'>
  }
  experiment_description: Rat HexMaze
  experimenter: ['Person']
  file_create_date: [datetime.datetime(2026, 7, 4, 13, 10, 38, 875083, tzinfo=tzoffset(None, 7200))]
  identifier: a4271704-65de-4d75-aa09-61da9a8a5345
  institution: Donders Institute, Radboud University
  keywords: <StrDataset for HDF5 dataset "keywords": shape (3,), type "|O">
  lab: Genzel Lab
  processing: {
    Behavior <class 'pynwb.base.ProcessingModule'>
  }
  related_publications: ['N/A']
  session_description: Rat1 Hexmaze Session op6
  session_id: op6
  session_start_time: 2026-06-29 10:37:44.137485+02:00
  subject: subject pynwb.file.Subject at 0x4601447824
Fields:
  age: P7Y179D
  age__reference: birth
  description: Rat 1
  sex: M
  species: Rattus norvegicus
  subject_id: 001

  timestamps_reference_time: 2026-06-29 10:37:44.137485+02:00
  units: units <class 'pynwb.misc.Units'>